### ISSUE TITLE
Update Accessibility and Markup for existing components

### ISSUE THREAD

**Issue by fspoettel** [propertybase/react-lds#136]
- [x] #191 — Card: Changed `.slds-card__footer` to a `<footer />` element
- [x] #189 — The `PageHeader` component "entity" icon is now contained within `.slds-icon_container`
- [x] #186 — Whenever `.slds-icon-text-default`, `.slds-icon-text-warning`, or `.slds-icon-text-error` is used, it is required to be used in conjunction with `.slds-icon`
- [x] Unless the HTML output is represented as a list — ul, ol, or dl — all examples were updated to use slds-bottom—[position] instead of slds-has-divider—[position]
- [x] Checkbox Group: Removed for attributes on wrapping span elements
- [x] Date Picker: Made the first day cell focusable as it is a ARIA grid widget
- [x] Avatar: Added missing title attributes
- [x] Whenever slds-truncate is used, it is required to be used in conjunction with a [title] attribute
- [x] Date Picker: Added role="dialog" to the slds-datepicker
 - [x] Date Picker: Added aria-label to the dialog to describe its purpose
  - [x] Date Picker: Added aria-multiselectable="true" to the grid to indicate you can selected multiple dates
 - [x] Date Picker: Removed headers attribute from each gridcell
 - [x] Date Picker: Added assistive text for when we mark today's date in the grid. We do this to provide additional meaning since the grey background color is not enough of an indicator to non-sighted users
 - [x] Date Picker: Changed the "Today" option to be a selectable cell, just like any other day in the grid, by removing its <a /> tag
  - [x]  Menus: Added aria-checked to Menu items with role="menuitemcheckbox" in all cases. Shouldn't just be added when true, setting false is important to communicate
 - [x] Modals: Added aria-describedby to the slds-modal element. This points to ID of slds-modal__content
Added aria-label to Header Empty example, in the absence of a header with a heading tag
  - [x] Pills: Add title attributes to all icons or avatars in a Pill
 - [x] Prompt: Added an ID to slds-modal__content for aria-describedby to work on the alertdialog
 - [x] Select: Added missing required attribute to Required and Error states
 - [x] Tabs: Fixed Sub Tabs tabpanels ID typos
- [x] Picklist: Upgrade the ARIA Combobox markup to ARIA 1.1 Specification
Moved role="combobox" attribute from the input element to slds-picklist root element
Moved aria-expanded="true|false" attribute from the input element to slds-picklist root element
Added aria-haspopup attribute to slds-picklist root element
Added autocomplete="off" to the input element
Added aria-controls="" to the input element which points to the ID of the listbox
Added role="textbox" to the input element
Removed aria-owns attribute from the input element as the listbox is not a child of the combobox role
Changed type attribute on the input element to be text
Changed the expand trigger button title attribute to match button text
Moved the ID from slds-dropdown__list to slds-dropdown with role="listbox"

**Comment by brunottonurb** [comment]
Can I combine PR here? Such small changes.

@fspoettel what do you mean with:
"Pills: Add title attributes to all icons or avatars in a Pill"
AFAIK pills get passed an Avatar or Icon which renders the title.

**Comment by brunottonurb** [comment]
Modals are missing .slds-modal__header_empty when header is emtpy. Will add together with the aria-label attr soon

**Comment by brunottonurb** [comment]
> Tabs: Fixed Sub Tabs tabpanels ID typos
What typos?

**Comment by fspoettel** [comment]
@brunottonurb could be that they meant a bug on their demo site here, i copy-pasted most stuff from the changelog

**Comment by carlo** [comment]
@fspoettel: what do you mean by

>  Checkbox Group: Removed for attributes on wrapping span elements

AFAICT this branch of react-lds produces the checkbox markup exactly [as the LDS proposes it](https://lightningdesignsystem.com/components/checkbox/). Is this done, then?

**Comment by fspoettel** [comment]
@carlo it's done then. the changelog has a lot of non-sense in it (or stuff they introduced and fixed between versions it seems). I went ahead and marked it as completed
