### ISSUE TITLE
Update to latest LDS

### ISSUE THREAD

**Issue by fspoettel** [propertybase/react-lds#250]
# Existing Components

## Badges

- [x] ~~Added dark blue badge~~
- [x] ~~Added white badge with icon and normalized text~~
- [x] ~~Add support for Icons in Badges~~

#253 

**Note:** As per [these docs](https://lightningdesignsystem.com/components/badges) theming has been removed from `<Badge />`, but it still works. New Badges are extremely limited, I left theming in our code but marked it as deprecated in the docs.

## Button Group

- [x] ~~Button menu uses filled button icon modifier by default~~
- [x] ~~Example: Icon-only groups~~

## Button Icons

- [x] ~~Added new branding variant~~

**Note:** Could not find branding variant in docs, ignoring

## Progress Bar

- [x] ~~Added green variant~~

#256

## Cards

- [x] ~~Added slds-card_boundary class to provide card-like look when component is inside a tabset~~ #260 

## Data Tables

- [x] ~~Added icons to data table headers and cells~~
- [x] ~~Added header menu buttons to table headers~~
- [x] ~~Added slds-table_column-*-wrap to add column wrap support~~ **DOCS MISSING**

**Note**: We support these via `cellRenderer` and `headRenderer` but do not have these undocumented icons yet. skipping.

## Grids

- [x] ~~Added top level gutter classes: slds-gutters and slds-gutters_* for sizes~~ #257

## Icons

- [x] ~~Added utility class slds-current-color to set an icon to use current color~~

**Note:** _We can set this via `className` or `svgClassName` in our components, so there is no need to change anything right now. This is a nice addition._

## Spinners

 - [x] ~~Added class slds-spinner_delayed to apply a 300ms delay to the animation~~

#255 

## Alerts

- [x] ~~Rename Notifications to Alerts~~ #261 

# pba-react

> With the changes to the page background color, you may notice some of your custom components are transparent, rendering the text on the dark background. You can fix that easily by adding the class .slds-card to the outer wrapper of your component.

> Updated Color guidelines to include Gray palette and Brand Colors

> Reduced and updated gray palettes to 12 total

# New Components

- [x] ~~Progress Ring~~ #263 
- [x] ~~Carousel~~ #259 
- [x] ~~Brand Band~~ #258

**Comment by fspoettel** [comment]
# Not in this version

- [ ] Map
