### ISSUE TITLE
Repository Cleanup

### ISSUE THREAD

**Issue by fspoettel** [propertybase/react-lds#40]
before open-sourcing this, the following has to be done:
- [x] ~~`<IconSVG>` adds `.slds-icon-sprite-name`-classes that add backgrounds to the icons in the latest version of LDS. This should be optional as it is not wanted in all cases (see ModalHeader as an unwanted example that broke with the latest LDS-Release)~~ #41 
- [x] ~~The unit-tests need to be rewritten in a consistent fashion. They are all over the place~~ #53
- [x] ~~BUG: Fix propTypeDescription and functions~~ #52 
- [x] ~~Indicate non-existent and unfinished components in the Demo App~~ #52 
- [x] ~~BUG: Fix nested routes~~ #52 
- [x] ~~Some ❤️ for the README would be nice~~ #52
- [x] The Component API needs to be consistent. Some components still don't fully use our decorators (e.g. `<Button>`). Others have no behavior while they probably should (Modal & Prompts)
